version: '3.3'
services:
  client-service:
    build: './client-service'
    ports:
      - "3000:3000"
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: backend-service
    depends_on:
      - mongo
    ports:
      - 8000:8080
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"